---
- name : Install Docker packages
  package:
    name: "{{ packages }}"
    state: latest
  register: docker_install

- name : Restart Docker daemon
  service: 
    name: docker.service
    state: restarted
    enabled: yes
  when: docker_install.changed

- name : "Add {{ ansible_user }} to docker group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
